Regional reports
WFP-VAM/mvam_infographics pull request #1
Opened 2020-11-17 09:14 UTC by maxmalynowsky

Breaking up Python `data_etl` into a `raw` and `global_insights` section, so the second can be re-run multiple times with different parameters, with the eventual output creating multiple regional reports.

2020-11-24 16:08 UTC, matteocorea requested changes
Nice!
Comments to be addressed, but definitely this goes in the right direction.

2020-11-24 16:08 UTC, matteocorea commented on src/data/covid-all-global.ts
> +import covidGlobal from '../../data/global_insights/covid_all_global.json';
I'm lost. What's the difference here? Is it just renaming for consistency?

2020-12-08 16:36 UTC, matteocorea requested changes
Review finally done!
Few comments to address, overall (I mean: considering the amount of files in this PR the number of comments is relatively small).

2020-12-08 16:36 UTC, matteocorea commented on data_etl/global_insights/metrics.py
> +    for c in l3:
I don't like `c` as a variable name. Can we go with something like `item`?

2020-12-08 16:36 UTC, matteocorea commented on upload/main.py
> +    # oss.clean_directory(directory)
Please don't commit commented code, if possible.
This is still TODO, right?

2020-12-08 16:36 UTC, matteocorea commented on upload/ossutils.py
> +        total_size = self.bucket.head_object(src_object).content_length
Fragment copy via `upload_part_copy` is needed only for files > 1GB. You can definitely use `bucket.copy_object` in this case, and reduce this whole method to a couple of lines.

2020-12-08 16:36 UTC, matteocorea commented on upload/ossutils.py
> +            dst_object = obj.key.replace(directory,latest_dir)
I don't like much this string replacement. It's risky.
I think what we should implement is something like
```
clean_directory(current_day_directory)
clean_directory(LATEST_DIRECTORY)
for report_name in available_files:
   self.save_file(report_name, current_day_directory)
   self.copy_file(report_name, current_day_directory, LATEST_DIRECTORY)
```

2020-12-08 16:36 UTC, matteocorea commented on upload/main.py
> +    # oss.clean_directory(directory)
Also, see comments in the `ossutils.py` file for general code structure

2020-12-08 16:36 UTC, matteocorea commented on upload/main.py
> +if __name__ == '__main__':
This needs to be added to the main.sh, right?
We might even want to make this a module, for consistency.

2020-12-09 11:16 UTC, maxmalynowsky commented on vega/styles.ts
> +  mark: { invalid: null },
We need this otherwise countries with no data have their polygons filtered out, which is the default behavior if this property isn't set. We want to keep them and colour them white instead.

2020-12-09 11:25 UTC, maxmalynowsky commented on src/components/annex/deep-dive.tsx
> +      title: 'Asia and the Pacific',
The way things are set up, the config only points to the currently active region, so every config would have to be changed to carry information about every other region, which doesn't quite cut down on the duplication.

2020-12-09 11:37 UTC, maxmalynowsky commented on src/components/annex/deep-dive.tsx
> +          link: `${baseUrl}/${config.name}-covid.pdf#page=4`,
The alternative of using `indexOf('covid-market')` also depends on us remembering to update that name reference in case we change it to 'covid-market-overview' or something like that, so this is going to remain sensitive to either name or position.

2020-12-09 11:56 UTC, maxmalynowsky commented on src/data/metrics.ts
> +  if (a.country.name < b.country.name) return -1;
Ah, didn't know this existed

2020-12-09 12:01 UTC, maxmalynowsky commented on vega/render.ts
> +export const renderPNG = async (project: string, name: string, vlSpec: any) => {
Was used for debugging the overview map, and I'd just want to keep them in to be able to do that in the future again if required, which is why they're named exports rather than default ones.

2020-12-10 08:22 UTC, matteocorea commented on src/components/annex/deep-dive.tsx
> +      title: 'Asia and the Pacific',
I was thinking more like:

- the python creates a config.json for the current report (as is now)
- the python also creates a json configuration with everything, just for cases like this. Something like config-full.json
- in the config .ts file we export the current config (as is now), but also anything else we need (like a map of all the report id to name, which is needed in the last page)
- unless you explicitly need to deal with the other reports, you only refer to config.json

2020-12-10 08:24 UTC, matteocorea commented on src/components/annex/deep-dive.tsx
> +          link: `${baseUrl}/${config.name}-covid.pdf#page=4`,
And still, it's much easier for the number to shift, for example if we add or remove pages before that one, while a name change is way less likely.
Point taken, the solution is not perfect. But still, it would be easier for us to make changes to the document and avoid introducing bugs without noticing (if we add/remove pages before the covid one, the silent effect is that the covid link will start pointing to another random page)

2020-12-10 08:26 UTC, matteocorea commented on vega/render.ts
> +export const renderPNG = async (project: string, name: string, vlSpec: any) => {
seems good. Thanks

2020-12-10 08:26 UTC, matteocorea commented on vega/styles.ts
> +  mark: { invalid: null },
ah I see. Thanks.

2020-12-10 11:51 UTC, maxmalynowsky commented on src/data/metrics-increase.ts
> +        (x.current.conflict.fatalities_incidence >= threshold ||
No, this one is not applied to the entire condition, and should be left as is

2020-12-11 10:02 UTC, matteocorea approved these changes
Ok! Let's merge!

2020-12-11 10:03 UTC, merged