Post regional optimizations
WFP-VAM/mvam_infographics pull request #3
Opened 2020-12-14 10:05 UTC by maxmalynowsky

The following structural changes have been implemented to simplify overall architecture of the repository:

data_etl/common/
- create data_etl.common module for mixing-in of separate API's into restructured data objects, data here can be consumed by either global or country insights.
- Data structure of all outputs are the same, so attributes like `x.country.iso3` or `x.covid.cases.incidence` are always present even when switching between sources (like metrics.json and covid.json).   
- Removed all global aggregations of data, since this needed to be re-calculated for each region.
Following outputs remain:
    - metrics.json: the default data object, should be used wherever possible.
    - metrics_increase.json: should only be accessed to get 3-month difference and severity tier / deterioration data
    - (covid / conflict).json: only for accessing data about non- hunger map related countries, rarely used in report now.

data_etl/global_insights/
- Mostly involved with creating the configs for different reports.
- All configs are outputted as single file. To access a specific config within, use configs.find(x => x.name === 'name'). This is done to improve caching performance in builds.

vega/
- Not done: reducing redundancy in duplicate configurations, still required in the future.
- Logic behind chart iteration has been standardized between all, now generates all variants between reports at once.
- Iteration follows pattern of: for each config, for each metric, for each country.
- Output directory names standardized: conflict-xxx/, covid-xxx/, metrics-xxx/, world-map-xxx/

gatsby-node.js:
- ENV is back, since python and vega are now run as a single step, rather than re-run for each new report.
- To accommodate a future country-insights, use createPages API to iterate through pages/ components based on current ENV.
- There isn't currently any logic for country-insights, so this always generates global pages for now in the same way as before.

src/global-insights/pages/
- No changes

src/global-insights/styles/
-  Not done: reducing redundancy in duplicate configurations, still required in the future.

src/global-insights/data/
- ALL: Since iso3 filtering is no longer done in Python, the first step of each file here performs that against the selected config.
- config.ts: now accessed current config through ENV
- Deleted unused global and (covid / conflict) logic that should be accessed through metrics instead.
- conflict / covid specific data all now deal with transformations that are not filtered by the current iso3 list.
- metrics-increase: already fairly optimized, no changes
- metrics: standardized structures of top 12 (prevalence / incidence) between (metrics / covid / conflict)

src/global-insights/components/
- Re-organize into sections that mirror new naming prefixes of pages (annex / common / conflict / covid / intro / metrics / school)
- Remove components from  common that are specific to only one section
- Attempt to eliminate redundancy between repeating (fcs / livelihoodCoping / marketAccess) sections, more can still be done.

puppeteer/
- Use static import logic of the new config and ENV, mostly the same as the previous version.
- To-do: break up into (common / global-insights / country-insights) modules.

2020-12-22 15:44 UTC, matteocorea requested changes
Hey Max,

Can you please resubmit the review making sure that if you rename a file (or a directory) you actually keep the link between the source file and the destination (I think `git mv` will do something like that). Otherwise I'd have to review from scratch all the `.ts` components instead of focusing only on the changes inside the files.

Thanks,

2020-12-22 15:44 UTC, matteocorea commented on data_etl/common/metrics.py
> +            del country['fatalities']
You're deleting fields from the input data from within a function meant to `add_conflict_additional_info`.
This is generally not desirable. If you really need to, create a copy and modify that instead

2020-12-22 15:44 UTC, matteocorea commented on src/global-insights/components/common/format-name.tsx
> +import React from 'react';
Please make sure to rename (`git mv` or something like that) all the files instead of simply renaming in the filesystem. This will keep the history of the file and will not show as a removed + added couple of files in the PR.

2020-12-24 14:00 UTC, matteocorea requested changes
Overall great optimizations! I really like where this is going!
Relatively few comments to address, and we're almost good to go.

2020-12-24 14:06 UTC, maxmalynowsky commented on gatsby-node.js
> +// const fs = require('fs');
This breaks the build function since I moved up everything up one level in the `src/` directory, it'll all be uncommented once that's reverted post-merge.

2020-12-24 14:08 UTC, maxmalynowsky commented on src/components/metrics/global-prevalence-fcs.tsx
> +  metric: {
Because the FCS page has very specific requirements like listing out the top 12 countries in the narrative, it wasn't easy to generalize this in a way that can be used by livelihood and markets, so I didn't completely finish merging them together, although that is the final intention.

2020-12-24 14:09 UTC, maxmalynowsky commented on src/components/metrics/global-prevalence-fcs.tsx
> +      number of people with insufficient food consumption&mdash;amounting to
Yep, that should be the case.

2020-12-24 14:11 UTC, maxmalynowsky commented on data_etl/common/metrics.py
> +            del country['fatalities']
I renamed the functions to be called `standardize_covid_data` and `standardize_conflict_data` so that it's more obvious what they do.

2020-12-24 14:13 UTC, maxmalynowsky commented on src/pages/global-insights/conflict-fcs.tsx
> +const metric = {
Just makes the code more consistent across the different components. That way every page looks the same, and have a familiar looking naming structure.

2020-12-24 14:14 UTC, maxmalynowsky commented on src/data/conflict.ts
>      .slice(0, 12),
All slicing in views has been removed. I tried slicing in views, but the amount of things that have to change are a lot, and it becomes much more difficult to guarantee that every view is handled correctly.

2020-12-24 14:18 UTC, maxmalynowsky commented on src/data/config.ts
> +const config = configs.find(x => x.name === env) ?? configs[0];
I wanted the default behaviour of running `yarn develop` / `yarn print` to default to something so that the development experience was a bit smoother. Adding `?? configs[0]` is meant to help out TypeScript error checking, so it doesn't give `property is possibly undefined` warnings unnecessarily.

2020-12-24 14:19 UTC, maxmalynowsky commented on src/data/conflict.ts
> +const data = conflict;
Used in the conflict global total number, this is the figure that includes countries that are not part of the 93 country list.

2020-12-24 14:24 UTC, maxmalynowsky commented on vega/global-insights/country-trend-metrics.ts
> +const globalConfig = configs.find(x => x.name === 'global') ?? configs[0];
TypeScript will give out `property is potentially undefined` errors unless this is included.

2020-12-24 14:25 UTC, maxmalynowsky commented on vega/global-insights/country-trend-conflict.ts
>  import render from '../render';
It is. As with merging the fcs/livelihood/market components in the metrics page, there just wasn't enough time to properly address this before creating the pull request, but I could take some time to look at it now.

2020-12-24 14:39 UTC, maxmalynowsky commented on vega/global-insights/country-trend-metrics.ts
> +const globalConfig = configs.find(x => x.name === 'global') ?? configs[0];
This is also consistent with how fallbacks are dealt with in the annex-dive component, preferring a name match, but falling back to position otherwise.

2020-12-24 14:56 UTC, maxmalynowsky commented on src/pages/global-insights/covid-livelihood.tsx
> +const metric = {
Yep, I think it should be a separate file, that would clean this up and reduce the likelihood of a typo.

2020-12-24 14:58 UTC, maxmalynowsky commented on vega/global-insights/index.ts
> +import './country-trend-conflict';
Yeah, I agree with that. Current implentation is a holdover from when a shell script was used to invoke them, which was only done because doing this before was resulting in memory overflow errors, which is now solved.

2020-12-24 15:00 UTC, maxmalynowsky commented on data_etl/common/metrics.py
> +            if (country['country']['iso3'] == 'CIV'):
I tried doing that, but the unicode representation kept ignoring the changes I wanted to make, whereas this was working consistently. I can try again with an override in a central place.

2021-01-06 12:07 UTC, matteocorea requested changes
This PR is GREAT! Only few other comments to address.

2021-01-06 12:11 UTC, maxmalynowsky commented on src/data/metrics-increase.ts
> +  x => x.days_ago === 90 && config.iso3.includes(x.country.iso3)
Turns out there isn't anywhere else in the entire codebase that refers to days_ago except here. Could be abstracted, but it would only be imported here.

2021-01-06 12:22 UTC, maxmalynowsky commented on vega/global-insights/country-trend-metrics.ts
> +if (typeof globalConfig === 'undefined')
It's only repeated in one other place, so I haven't abstracted it out. Could implement later if more charts use this.

2021-01-06 13:28 UTC, matteocorea approved these changes
Oh Yeah!

2021-01-06 13:28 UTC, merged